on: push
name: Run tests
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    container:
      image: rust:1.66
    steps:
      - uses: actions/checkout@v3
      - run: script/download-test-data.sh
      - run: cargo test
      - run: cargo test --features test_full
      - run: cargo bench --features test_full
